id: productFeature
name: Product Feature
created: '2023-10-17T05:56:16.285197+00:00'
updated: '2023-10-17T07:31:43.545809+00:00'
slugSettings:
  required: 'no'
fields:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig:
      multiline: true
      linesCount: 5
  - id: image
    name: Image
    type: image
    helpText: ''
    typeConfig: null
  - id: productId
    name: Product Id
    type: text
    helpText: ''
    typeConfig: null
entryName: title
description: ''
icon: file-document
type: contentType
